### ISSUE TITLE
ON CREATE/MATCH SET between MERGE clauses is not allowed

### ISSUE THREAD

**Issue by traxtech** [bitnine-oss/agensgraph#372]
Hi.

AgensGraph does not support chaining MERGE with ON CREATE/MATCH SET .. :

Caused by: org.postgresql.util.PSQLException: ERROR: ON CREATE/MATCH SET between MERGE clauses is not allowed
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at net.bitnine.agensgraph.jdbc.AgPreparedStatement.executeUpdate(AgPreparedStatement.java:65)

How can I work around that limitation without splitting the query in multiple ones ? And will it be fixed ?

Thanks.

**Comment by gtyun** [comment]
Hi, traxtech.
ON MATCH/CREATE SET are only available in the last MERGE clause. Otherwise, it can cause inconsistent data problem. 
Unfortunately we have no schedule for this.

**Comment by gtyun** [comment]
That inconsistent problem is resolved in develop version. So the grammar limit code could be removed. 
`MERGE ON .. SET .. MERGE` will be available in the next release. 
Thanks for your report.

**Comment by traxtech** [comment]
Ok, Thanks!
