### ISSUE TITLE
Agens FDW (Foreign Data Wrappers)  where can I get the jar file

### ISSUE THREAD

**Issue by VinACE** [bitnine-oss/agensgraph#414]
:/usr/local/pgsql/lib> jar cvf Hadoop_FDW.jar HadoopJDBCLoader.class HadoopJDBCUtils.class
HadoopJDBCLoader.class : no such file or directory
HadoopJDBCUtils.class : no such file or directory
java.io.FileNotFoundException: Hadoop_FDW.jar (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at sun.tools.jar.Main.run(Main.java:195)
        at sun.tools.jar.Main.main(Main.java:1288)

 where can I get the jar file

**Comment by bylee5** [comment]
I did "USE_PGXS=1 make install" to $AGHOME/contrib/hadoop_fdw.
I did "jar cvf Hadoop_FDW.jar HadoopJDBCLoader.class HadoopJDBCUtils.class" to $AGHOME/lib/postgresql.
