### ISSUE TITLE
ERROR:  java.lang.ClassNotFoundException: org.apache.hive.jdbc.HiveDriver

### ISSUE THREAD

**Issue by VinACE** [bitnine-oss/agensgraph#416]
batch=#  SELECT code, total_emp FROM sample_07 ORDER BY code LIMIT 3;
ERROR:  java.lang.ClassNotFoundException: org.apache.hive.jdbc.HiveDriver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at HadoopJDBCUtils.ConnInitialize(HadoopJDBCUtils.java:74)

I have copied the  jar files in to the following location,
/usr/local/pgsql/lib/hadoop_fdw/

hive-jdbc-2.1.0.2.6.5.8-7-standalone.jar
hadoop-common-2.8.3-amzn-0.jar

**Comment by bylee5** [comment]
I set the HADOOP_FDW_CLASSPATH environment variable.
The following is an example.
`HADOOP_FDW_CLASSPATH=$AGHOME/lib/postgresql/hive-jdbc-$HIVE_VER-standalone.jar:$AGHOME/lib/postgresql/hadoop-common-$HADOOP_VER.jar:$AGHOME/lib/postgresql/Hadoop_FDW.jar`

Additionally,
$AGHOME is agensgraph home. 
$HIVE_VER is Hive version. 
$HADOOP_VER is Hadoop version
