### ISSUE TITLE
org.postgresql.util.PSQLException is reported when executing the Cypher query: MATCH (n0) WHERE n0.k0 = "hello" RETURN n0.k0

### ISSUE THREAD

**Issue by abc123000111** [bitnine-oss/agensgraph#546]
I discovered that when I executed the following Cypher query:
MATCH (n0) WHERE n0.k0 = "hello" RETURN n0.k0
An error occurred:
**org.postgresql.util.PSQLException: ERROR: variable does not exist**
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260)
	at net.bitnine.agensgraph.jdbc.AgStatement.execute(AgStatement.java:113)

Version: 2.5.0
Operating System: Windows 11
API: Cypher/Java API

**Comment by emotionbug** [comment]
Single quotes for string constants, double quotes for table/column names in PG.

**Comment by abc123000111** [comment]
> Single quotes for string constants, double quotes for table/column names in PG.

Thanks a lot!
