### ISSUE TITLE
can not connect agens to java application with jdbc

### ISSUE THREAD

**Issue by coulibalyfagnine** [bitnine-oss/agensgraph#594]
Hello, I am trying to connect a java application but it does not work .
I am following this documentation : https://bitnine.net/documentations/quick-guide-2-0.html#client-drivers .
Can somebody help me please ?

**My code :**
Class.forName("net.bitnine.agensgraph.Driver");
		    String connectionString = "jdbc:agensgraph://127.0.0.1:5433/prospection_cube";
		    String username = "agens";
		    String password = "0000";
		    Connection conn = DriverManager.getConnection(connectionString, username, password);

**The error message in the console :** 
SEVERE: Connection error: 
org.postgresql.util.PSQLException: FATAL: authentification par mot de passe échouée pour l'utilisateur  « agens » (pgjdbc: autodetected server-encoding to be ISO-8859-1, if the message is not readable, please check database logs and/or host, port, dbname, user, password, pg_hba.conf)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:438)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
	at net.bitnine.agensgraph.jdbc.AgConnection.<init>(AgConnection.java:39)
	at net.bitnine.agensgraph.Driver.makeConnection(Driver.java:466)
	at net.bitnine.agensgraph.Driver.connect(Driver.java:268)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at test_agens_connexion.AppAgens.main(AppAgens.java:18)

**Comment by emotionbug** [comment]
Check your username and password.

**Comment by coulibalyfagnine** [comment]
Think [emotionbug](https://github.com/emotionbug) for replying!
Indeed, I use the password that I provided for the user "agens" in the installation of agensgraph.
I even uninstall and reinstall agens to make sure that I get that right but still.
Is there a configuration file where I can see all user and password for agensgraph ?
kind regard.

**Comment by emotionbug** [comment]
Please refer to the document below.
https://www.postgresql.org/docs/current/client-authentication.html
